---
.cache_bundler: &cache_bundler
  cache:
    untracked: true
    # An attempt at caching between runs (ala Travis CI)
    key: "${CI_PROJECT_NAMESPACE}__bundler"
    paths:
      - '.vendor'
      - 'vendor'

.setup_bundler_env: &setup_bundler_env
  before_script:
    - '(find .vendor | wc -l) || :'
    - bundle || gem install bundler --no-rdoc --no-ri
    - rm -rf Gemfile.lock pkg/
    - bundle install --no-binstubs --jobs $(nproc) --path .vendor "${FLAGS[@]}"

.static_tests: &static_tests
  script:
    - bundle exec rake syntax
    - bundle exec rake lint
    - bundle exec rake check:dot_underscore
    - bundle exec rake check:test_file
    - bundle exec rake pkg:check_version
    - bundle exec rake pkg:compare_latest_tag
    - bundle exec rake spec
    - bundle exec puppet module build

stages:
  - unit
  - acceptance
  - deploy

# Puppet 4
puppet-gemfile:
  stage: unit
  tags:
    - docker
  image: ruby:2.1.9
  <<: *cache_bundler
  <<: *setup_bundler_env
  <<: *static_tests

# For PE LTS Support
# See: https://puppet.com/misc/puppet-enterprise-lifecycle
puppet-4.7:
  stage: unit
  tags:
    - docker
  image: ruby:2.1.9
  variables:
    PUPPET_VERSION: '4.7'
  <<: *cache_bundler
  <<: *setup_bundler_env
  <<: *static_tests

puppet-5:
  stage: unit
  tags:
    - docker
  image: ruby:2.4
  variables:
    PUPPET_VERSION: '5.0'
  <<: *cache_bundler
  <<: *setup_bundler_env
  <<: *static_tests


default:
  stage: acceptance
  tags:
    - beaker
  <<: *cache_bundler
  <<: *setup_bundler_env
  variables:
    PUPPET_VERSION: '4.10'
  script:
    - bundle exec rake beaker:suites[default]

default-fips:
  stage: acceptance
  tags:
    - beaker
  <<: *cache_bundler
  <<: *setup_bundler_env
  variables:
    BEAKER_fips: 'yes'
    PUPPET_VERSION: '4.10'
  script:
    - bundle exec rake beaker:suites[default]

default-latest:
  stage: acceptance
  tags:
    - beaker
  <<: *cache_bundler
  <<: *setup_bundler_env
  variables:
    PUPPET_VERSION: '5.0.0'
  script:
    - bundle exec rake beaker:suites[default]
  allow_failure: true
